/*
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class PartiturWebModule extends AbstractPartiturWebModule {
}
