/*
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PartiturAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("io/beethoven/partitur/parser/antlr/internal/InternalPartitur.tokens");
	}
}
