/*
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.parser.antlr;

import com.google.inject.Inject;
import io.beethoven.partitur.parser.antlr.internal.InternalPartiturParser;
import io.beethoven.partitur.services.PartiturGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PartiturParser extends AbstractAntlrParser {

	@Inject
	private PartiturGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPartiturParser createParser(XtextTokenStream stream) {
		return new InternalPartiturParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "PartiturWorkflow";
	}

	public PartiturGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PartiturGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
