/*
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPartiturScopeProvider extends DelegatingScopeProvider {
}
