/*
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PartiturStandaloneSetup extends PartiturStandaloneSetupGenerated {

	def static void doSetup() {
		new PartiturStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
