/*
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PartiturRuntimeModule extends AbstractPartiturRuntimeModule {
}
