/*
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.ide.contentassist.antlr;

import com.google.inject.Inject;
import io.beethoven.partitur.ide.contentassist.antlr.internal.InternalPartiturParser;
import io.beethoven.partitur.services.PartiturGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class PartiturParser extends AbstractContentAssistParser {

	@Inject
	private PartiturGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalPartiturParser createParser() {
		InternalPartiturParser result = new InternalPartiturParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPartiturTaskAccess().getAlternatives_3(), "rule__PartiturTask__Alternatives_3");
					put(grammarAccess.getPartiturConditionFunctionAccess().getAlternatives(), "rule__PartiturConditionFunction__Alternatives");
					put(grammarAccess.getPartiturCommandFunctionAccess().getAlternatives(), "rule__PartiturCommandFunction__Alternatives");
					put(grammarAccess.getEventTypeAccess().getAlternatives(), "rule__EventType__Alternatives");
					put(grammarAccess.getPartiturWorkflowAccess().getGroup(), "rule__PartiturWorkflow__Group__0");
					put(grammarAccess.getPartiturTaskAccess().getGroup(), "rule__PartiturTask__Group__0");
					put(grammarAccess.getPartiturHandlerAccess().getGroup(), "rule__PartiturHandler__Group__0");
					put(grammarAccess.getPartiturHandlerAccess().getGroup_7(), "rule__PartiturHandler__Group_7__0");
					put(grammarAccess.getPartiturHandlerAccess().getGroup_10(), "rule__PartiturHandler__Group_10__0");
					put(grammarAccess.getPartiturConditionAccess().getGroup(), "rule__PartiturCondition__Group__0");
					put(grammarAccess.getPartiturCommandAccess().getGroup(), "rule__PartiturCommand__Group__0");
					put(grammarAccess.getHttpGetAccess().getGroup(), "rule__HttpGet__Group__0");
					put(grammarAccess.getHttpPostAccess().getGroup(), "rule__HttpPost__Group__0");
					put(grammarAccess.getHttpPutAccess().getGroup(), "rule__HttpPut__Group__0");
					put(grammarAccess.getHttpDeleteAccess().getGroup(), "rule__HttpDelete__Group__0");
					put(grammarAccess.getHttpHeaderAccess().getGroup(), "rule__HttpHeader__Group__0");
					put(grammarAccess.getUriVariablesAccess().getGroup(), "rule__UriVariables__Group__0");
					put(grammarAccess.getUriVariablesAccess().getGroup_2(), "rule__UriVariables__Group_2__0");
					put(grammarAccess.getQueryParamAccess().getGroup(), "rule__QueryParam__Group__0");
					put(grammarAccess.getHttpBodyAccess().getGroup(), "rule__HttpBody__Group__0");
					put(grammarAccess.getPartiturWorkflowAccess().getNameAssignment_1(), "rule__PartiturWorkflow__NameAssignment_1");
					put(grammarAccess.getPartiturWorkflowAccess().getTasksAssignment_3(), "rule__PartiturWorkflow__TasksAssignment_3");
					put(grammarAccess.getPartiturWorkflowAccess().getHandlersAssignment_4(), "rule__PartiturWorkflow__HandlersAssignment_4");
					put(grammarAccess.getPartiturTaskAccess().getNameAssignment_1(), "rule__PartiturTask__NameAssignment_1");
					put(grammarAccess.getPartiturTaskAccess().getPartiturHttpRequestAssignment_3_0(), "rule__PartiturTask__PartiturHttpRequestAssignment_3_0");
					put(grammarAccess.getPartiturTaskAccess().getPartiturHttpRequestAssignment_3_1(), "rule__PartiturTask__PartiturHttpRequestAssignment_3_1");
					put(grammarAccess.getPartiturTaskAccess().getPartiturHttpRequestAssignment_3_2(), "rule__PartiturTask__PartiturHttpRequestAssignment_3_2");
					put(grammarAccess.getPartiturTaskAccess().getPartiturHttpRequestAssignment_3_3(), "rule__PartiturTask__PartiturHttpRequestAssignment_3_3");
					put(grammarAccess.getPartiturHandlerAccess().getNameAssignment_1(), "rule__PartiturHandler__NameAssignment_1");
					put(grammarAccess.getPartiturHandlerAccess().getEventAssignment_4(), "rule__PartiturHandler__EventAssignment_4");
					put(grammarAccess.getPartiturHandlerAccess().getConditionsAssignment_6(), "rule__PartiturHandler__ConditionsAssignment_6");
					put(grammarAccess.getPartiturHandlerAccess().getConditionsAssignment_7_1(), "rule__PartiturHandler__ConditionsAssignment_7_1");
					put(grammarAccess.getPartiturHandlerAccess().getCommandsAssignment_9(), "rule__PartiturHandler__CommandsAssignment_9");
					put(grammarAccess.getPartiturHandlerAccess().getCommandsAssignment_10_1(), "rule__PartiturHandler__CommandsAssignment_10_1");
					put(grammarAccess.getPartiturConditionAccess().getConditionFunctionAssignment_0(), "rule__PartiturCondition__ConditionFunctionAssignment_0");
					put(grammarAccess.getPartiturConditionAccess().getArgAssignment_2(), "rule__PartiturCondition__ArgAssignment_2");
					put(grammarAccess.getPartiturCommandAccess().getCommandFunctionAssignment_0(), "rule__PartiturCommand__CommandFunctionAssignment_0");
					put(grammarAccess.getPartiturCommandAccess().getArgAssignment_2(), "rule__PartiturCommand__ArgAssignment_2");
					put(grammarAccess.getHttpGetAccess().getUrlAssignment_2(), "rule__HttpGet__UrlAssignment_2");
					put(grammarAccess.getHttpGetAccess().getUriVariablesAssignment_4(), "rule__HttpGet__UriVariablesAssignment_4");
					put(grammarAccess.getHttpGetAccess().getHeadersAssignment_5(), "rule__HttpGet__HeadersAssignment_5");
					put(grammarAccess.getHttpGetAccess().getParamsAssignment_6(), "rule__HttpGet__ParamsAssignment_6");
					put(grammarAccess.getHttpPostAccess().getUrlAssignment_2(), "rule__HttpPost__UrlAssignment_2");
					put(grammarAccess.getHttpPostAccess().getUriVariablesAssignment_4(), "rule__HttpPost__UriVariablesAssignment_4");
					put(grammarAccess.getHttpPostAccess().getHeadersAssignment_5(), "rule__HttpPost__HeadersAssignment_5");
					put(grammarAccess.getHttpPostAccess().getBodyAssignment_6(), "rule__HttpPost__BodyAssignment_6");
					put(grammarAccess.getHttpPutAccess().getUrlAssignment_2(), "rule__HttpPut__UrlAssignment_2");
					put(grammarAccess.getHttpPutAccess().getUriVariablesAssignment_4(), "rule__HttpPut__UriVariablesAssignment_4");
					put(grammarAccess.getHttpPutAccess().getHeadersAssignment_5(), "rule__HttpPut__HeadersAssignment_5");
					put(grammarAccess.getHttpPutAccess().getBodyAssignment_6(), "rule__HttpPut__BodyAssignment_6");
					put(grammarAccess.getHttpDeleteAccess().getUrlAssignment_2(), "rule__HttpDelete__UrlAssignment_2");
					put(grammarAccess.getHttpDeleteAccess().getUriVariablesAssignment_4(), "rule__HttpDelete__UriVariablesAssignment_4");
					put(grammarAccess.getHttpDeleteAccess().getHeadersAssignment_5(), "rule__HttpDelete__HeadersAssignment_5");
					put(grammarAccess.getHttpHeaderAccess().getNameAssignment_1(), "rule__HttpHeader__NameAssignment_1");
					put(grammarAccess.getHttpHeaderAccess().getValueAssignment_3(), "rule__HttpHeader__ValueAssignment_3");
					put(grammarAccess.getUriVariablesAccess().getValuesAssignment_1(), "rule__UriVariables__ValuesAssignment_1");
					put(grammarAccess.getUriVariablesAccess().getValuesAssignment_2_1(), "rule__UriVariables__ValuesAssignment_2_1");
					put(grammarAccess.getQueryParamAccess().getNameAssignment_1(), "rule__QueryParam__NameAssignment_1");
					put(grammarAccess.getQueryParamAccess().getValueAssignment_3(), "rule__QueryParam__ValueAssignment_3");
					put(grammarAccess.getHttpBodyAccess().getValueAssignment_1(), "rule__HttpBody__ValueAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PartiturGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PartiturGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
