/*
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractPartiturValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(io.beethoven.partitur.partitur.PartiturPackage.eINSTANCE);
		return result;
	}
	
}
