/*
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link PartiturWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractPartiturWebModule extends DefaultWebModule {

}
