/**
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.partitur;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Http Post</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.beethoven.partitur.partitur.HttpPost#getUrl <em>Url</em>}</li>
 *   <li>{@link io.beethoven.partitur.partitur.HttpPost#getUriVariables <em>Uri Variables</em>}</li>
 *   <li>{@link io.beethoven.partitur.partitur.HttpPost#getHeaders <em>Headers</em>}</li>
 *   <li>{@link io.beethoven.partitur.partitur.HttpPost#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see io.beethoven.partitur.partitur.PartiturPackage#getHttpPost()
 * @model
 * @generated
 */
public interface HttpPost extends EObject
{
  /**
   * Returns the value of the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Url</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' attribute.
   * @see #setUrl(String)
   * @see io.beethoven.partitur.partitur.PartiturPackage#getHttpPost_Url()
   * @model
   * @generated
   */
  String getUrl();

  /**
   * Sets the value of the '{@link io.beethoven.partitur.partitur.HttpPost#getUrl <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Url</em>' attribute.
   * @see #getUrl()
   * @generated
   */
  void setUrl(String value);

  /**
   * Returns the value of the '<em><b>Uri Variables</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Uri Variables</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uri Variables</em>' containment reference.
   * @see #setUriVariables(UriVariables)
   * @see io.beethoven.partitur.partitur.PartiturPackage#getHttpPost_UriVariables()
   * @model containment="true"
   * @generated
   */
  UriVariables getUriVariables();

  /**
   * Sets the value of the '{@link io.beethoven.partitur.partitur.HttpPost#getUriVariables <em>Uri Variables</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uri Variables</em>' containment reference.
   * @see #getUriVariables()
   * @generated
   */
  void setUriVariables(UriVariables value);

  /**
   * Returns the value of the '<em><b>Headers</b></em>' containment reference list.
   * The list contents are of type {@link io.beethoven.partitur.partitur.HttpHeader}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Headers</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Headers</em>' containment reference list.
   * @see io.beethoven.partitur.partitur.PartiturPackage#getHttpPost_Headers()
   * @model containment="true"
   * @generated
   */
  EList<HttpHeader> getHeaders();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(HttpBody)
   * @see io.beethoven.partitur.partitur.PartiturPackage#getHttpPost_Body()
   * @model containment="true"
   * @generated
   */
  HttpBody getBody();

  /**
   * Sets the value of the '{@link io.beethoven.partitur.partitur.HttpPost#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(HttpBody value);

} // HttpPost
