/**
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.partitur;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.beethoven.partitur.partitur.PartiturCommand#getCommandFunction <em>Command Function</em>}</li>
 *   <li>{@link io.beethoven.partitur.partitur.PartiturCommand#getArg <em>Arg</em>}</li>
 * </ul>
 *
 * @see io.beethoven.partitur.partitur.PartiturPackage#getPartiturCommand()
 * @model
 * @generated
 */
public interface PartiturCommand extends EObject
{
  /**
   * Returns the value of the '<em><b>Command Function</b></em>' attribute.
   * The literals are from the enumeration {@link io.beethoven.partitur.partitur.PartiturCommandFunction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Command Function</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command Function</em>' attribute.
   * @see io.beethoven.partitur.partitur.PartiturCommandFunction
   * @see #setCommandFunction(PartiturCommandFunction)
   * @see io.beethoven.partitur.partitur.PartiturPackage#getPartiturCommand_CommandFunction()
   * @model
   * @generated
   */
  PartiturCommandFunction getCommandFunction();

  /**
   * Sets the value of the '{@link io.beethoven.partitur.partitur.PartiturCommand#getCommandFunction <em>Command Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command Function</em>' attribute.
   * @see io.beethoven.partitur.partitur.PartiturCommandFunction
   * @see #getCommandFunction()
   * @generated
   */
  void setCommandFunction(PartiturCommandFunction value);

  /**
   * Returns the value of the '<em><b>Arg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arg</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg</em>' attribute.
   * @see #setArg(String)
   * @see io.beethoven.partitur.partitur.PartiturPackage#getPartiturCommand_Arg()
   * @model
   * @generated
   */
  String getArg();

  /**
   * Sets the value of the '{@link io.beethoven.partitur.partitur.PartiturCommand#getArg <em>Arg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg</em>' attribute.
   * @see #getArg()
   * @generated
   */
  void setArg(String value);

} // PartiturCommand
