/**
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.partitur;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Workflow</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.beethoven.partitur.partitur.PartiturWorkflow#getName <em>Name</em>}</li>
 *   <li>{@link io.beethoven.partitur.partitur.PartiturWorkflow#getTasks <em>Tasks</em>}</li>
 *   <li>{@link io.beethoven.partitur.partitur.PartiturWorkflow#getHandlers <em>Handlers</em>}</li>
 * </ul>
 *
 * @see io.beethoven.partitur.partitur.PartiturPackage#getPartiturWorkflow()
 * @model
 * @generated
 */
public interface PartiturWorkflow extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.beethoven.partitur.partitur.PartiturPackage#getPartiturWorkflow_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.beethoven.partitur.partitur.PartiturWorkflow#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
   * The list contents are of type {@link io.beethoven.partitur.partitur.PartiturTask}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tasks</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference list.
   * @see io.beethoven.partitur.partitur.PartiturPackage#getPartiturWorkflow_Tasks()
   * @model containment="true"
   * @generated
   */
  EList<PartiturTask> getTasks();

  /**
   * Returns the value of the '<em><b>Handlers</b></em>' containment reference list.
   * The list contents are of type {@link io.beethoven.partitur.partitur.PartiturHandler}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Handlers</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Handlers</em>' containment reference list.
   * @see io.beethoven.partitur.partitur.PartiturPackage#getPartiturWorkflow_Handlers()
   * @model containment="true"
   * @generated
   */
  EList<PartiturHandler> getHandlers();

} // PartiturWorkflow
