/**
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.partitur;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.beethoven.partitur.partitur.PartiturTask#getName <em>Name</em>}</li>
 *   <li>{@link io.beethoven.partitur.partitur.PartiturTask#getPartiturHttpRequest <em>Partitur Http Request</em>}</li>
 * </ul>
 *
 * @see io.beethoven.partitur.partitur.PartiturPackage#getPartiturTask()
 * @model
 * @generated
 */
public interface PartiturTask extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.beethoven.partitur.partitur.PartiturPackage#getPartiturTask_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.beethoven.partitur.partitur.PartiturTask#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Partitur Http Request</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Partitur Http Request</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Partitur Http Request</em>' containment reference.
   * @see #setPartiturHttpRequest(EObject)
   * @see io.beethoven.partitur.partitur.PartiturPackage#getPartiturTask_PartiturHttpRequest()
   * @model containment="true"
   * @generated
   */
  EObject getPartiturHttpRequest();

  /**
   * Sets the value of the '{@link io.beethoven.partitur.partitur.PartiturTask#getPartiturHttpRequest <em>Partitur Http Request</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Partitur Http Request</em>' containment reference.
   * @see #getPartiturHttpRequest()
   * @generated
   */
  void setPartiturHttpRequest(EObject value);

} // PartiturTask
