/**
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.partitur;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see io.beethoven.partitur.partitur.PartiturFactory
 * @model kind="package"
 * @generated
 */
public interface PartiturPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "partitur";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.beethoven.io/partitur/Partitur";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "partitur";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PartiturPackage eINSTANCE = io.beethoven.partitur.partitur.impl.PartiturPackageImpl.init();

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.impl.PartiturWorkflowImpl <em>Workflow</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.impl.PartiturWorkflowImpl
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturWorkflow()
   * @generated
   */
  int PARTITUR_WORKFLOW = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_WORKFLOW__NAME = 0;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_WORKFLOW__TASKS = 1;

  /**
   * The feature id for the '<em><b>Handlers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_WORKFLOW__HANDLERS = 2;

  /**
   * The number of structural features of the '<em>Workflow</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_WORKFLOW_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.impl.PartiturTaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.impl.PartiturTaskImpl
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturTask()
   * @generated
   */
  int PARTITUR_TASK = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Partitur Http Request</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_TASK__PARTITUR_HTTP_REQUEST = 1;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_TASK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.impl.PartiturHandlerImpl <em>Handler</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.impl.PartiturHandlerImpl
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturHandler()
   * @generated
   */
  int PARTITUR_HANDLER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_HANDLER__NAME = 0;

  /**
   * The feature id for the '<em><b>Event</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_HANDLER__EVENT = 1;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_HANDLER__CONDITIONS = 2;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_HANDLER__COMMANDS = 3;

  /**
   * The number of structural features of the '<em>Handler</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_HANDLER_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.impl.PartiturConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.impl.PartiturConditionImpl
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturCondition()
   * @generated
   */
  int PARTITUR_CONDITION = 3;

  /**
   * The feature id for the '<em><b>Condition Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_CONDITION__CONDITION_FUNCTION = 0;

  /**
   * The feature id for the '<em><b>Arg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_CONDITION__ARG = 1;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_CONDITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.impl.PartiturCommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.impl.PartiturCommandImpl
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturCommand()
   * @generated
   */
  int PARTITUR_COMMAND = 4;

  /**
   * The feature id for the '<em><b>Command Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_COMMAND__COMMAND_FUNCTION = 0;

  /**
   * The feature id for the '<em><b>Arg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_COMMAND__ARG = 1;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTITUR_COMMAND_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.impl.HttpGetImpl <em>Http Get</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.impl.HttpGetImpl
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getHttpGet()
   * @generated
   */
  int HTTP_GET = 5;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_GET__URL = 0;

  /**
   * The feature id for the '<em><b>Uri Variables</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_GET__URI_VARIABLES = 1;

  /**
   * The feature id for the '<em><b>Headers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_GET__HEADERS = 2;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_GET__PARAMS = 3;

  /**
   * The number of structural features of the '<em>Http Get</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_GET_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.impl.HttpPostImpl <em>Http Post</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.impl.HttpPostImpl
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getHttpPost()
   * @generated
   */
  int HTTP_POST = 6;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_POST__URL = 0;

  /**
   * The feature id for the '<em><b>Uri Variables</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_POST__URI_VARIABLES = 1;

  /**
   * The feature id for the '<em><b>Headers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_POST__HEADERS = 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_POST__BODY = 3;

  /**
   * The number of structural features of the '<em>Http Post</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_POST_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.impl.HttpPutImpl <em>Http Put</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.impl.HttpPutImpl
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getHttpPut()
   * @generated
   */
  int HTTP_PUT = 7;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_PUT__URL = 0;

  /**
   * The feature id for the '<em><b>Uri Variables</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_PUT__URI_VARIABLES = 1;

  /**
   * The feature id for the '<em><b>Headers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_PUT__HEADERS = 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_PUT__BODY = 3;

  /**
   * The number of structural features of the '<em>Http Put</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_PUT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.impl.HttpDeleteImpl <em>Http Delete</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.impl.HttpDeleteImpl
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getHttpDelete()
   * @generated
   */
  int HTTP_DELETE = 8;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_DELETE__URL = 0;

  /**
   * The feature id for the '<em><b>Uri Variables</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_DELETE__URI_VARIABLES = 1;

  /**
   * The feature id for the '<em><b>Headers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_DELETE__HEADERS = 2;

  /**
   * The number of structural features of the '<em>Http Delete</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_DELETE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.impl.HttpHeaderImpl <em>Http Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.impl.HttpHeaderImpl
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getHttpHeader()
   * @generated
   */
  int HTTP_HEADER = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_HEADER__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_HEADER__VALUE = 1;

  /**
   * The number of structural features of the '<em>Http Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_HEADER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.impl.UriVariablesImpl <em>Uri Variables</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.impl.UriVariablesImpl
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getUriVariables()
   * @generated
   */
  int URI_VARIABLES = 10;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URI_VARIABLES__VALUES = 0;

  /**
   * The number of structural features of the '<em>Uri Variables</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URI_VARIABLES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.impl.QueryParamImpl <em>Query Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.impl.QueryParamImpl
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getQueryParam()
   * @generated
   */
  int QUERY_PARAM = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_PARAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_PARAM__VALUE = 1;

  /**
   * The number of structural features of the '<em>Query Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_PARAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.impl.HttpBodyImpl <em>Http Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.impl.HttpBodyImpl
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getHttpBody()
   * @generated
   */
  int HTTP_BODY = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_BODY__VALUE = 0;

  /**
   * The number of structural features of the '<em>Http Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTTP_BODY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.PartiturConditionFunction <em>Condition Function</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.PartiturConditionFunction
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturConditionFunction()
   * @generated
   */
  int PARTITUR_CONDITION_FUNCTION = 13;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.PartiturCommandFunction <em>Command Function</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.PartiturCommandFunction
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturCommandFunction()
   * @generated
   */
  int PARTITUR_COMMAND_FUNCTION = 14;

  /**
   * The meta object id for the '{@link io.beethoven.partitur.partitur.EventType <em>Event Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.beethoven.partitur.partitur.EventType
   * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getEventType()
   * @generated
   */
  int EVENT_TYPE = 15;


  /**
   * Returns the meta object for class '{@link io.beethoven.partitur.partitur.PartiturWorkflow <em>Workflow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Workflow</em>'.
   * @see io.beethoven.partitur.partitur.PartiturWorkflow
   * @generated
   */
  EClass getPartiturWorkflow();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.PartiturWorkflow#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.beethoven.partitur.partitur.PartiturWorkflow#getName()
   * @see #getPartiturWorkflow()
   * @generated
   */
  EAttribute getPartiturWorkflow_Name();

  /**
   * Returns the meta object for the containment reference list '{@link io.beethoven.partitur.partitur.PartiturWorkflow#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see io.beethoven.partitur.partitur.PartiturWorkflow#getTasks()
   * @see #getPartiturWorkflow()
   * @generated
   */
  EReference getPartiturWorkflow_Tasks();

  /**
   * Returns the meta object for the containment reference list '{@link io.beethoven.partitur.partitur.PartiturWorkflow#getHandlers <em>Handlers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Handlers</em>'.
   * @see io.beethoven.partitur.partitur.PartiturWorkflow#getHandlers()
   * @see #getPartiturWorkflow()
   * @generated
   */
  EReference getPartiturWorkflow_Handlers();

  /**
   * Returns the meta object for class '{@link io.beethoven.partitur.partitur.PartiturTask <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see io.beethoven.partitur.partitur.PartiturTask
   * @generated
   */
  EClass getPartiturTask();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.PartiturTask#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.beethoven.partitur.partitur.PartiturTask#getName()
   * @see #getPartiturTask()
   * @generated
   */
  EAttribute getPartiturTask_Name();

  /**
   * Returns the meta object for the containment reference '{@link io.beethoven.partitur.partitur.PartiturTask#getPartiturHttpRequest <em>Partitur Http Request</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Partitur Http Request</em>'.
   * @see io.beethoven.partitur.partitur.PartiturTask#getPartiturHttpRequest()
   * @see #getPartiturTask()
   * @generated
   */
  EReference getPartiturTask_PartiturHttpRequest();

  /**
   * Returns the meta object for class '{@link io.beethoven.partitur.partitur.PartiturHandler <em>Handler</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Handler</em>'.
   * @see io.beethoven.partitur.partitur.PartiturHandler
   * @generated
   */
  EClass getPartiturHandler();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.PartiturHandler#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.beethoven.partitur.partitur.PartiturHandler#getName()
   * @see #getPartiturHandler()
   * @generated
   */
  EAttribute getPartiturHandler_Name();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.PartiturHandler#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Event</em>'.
   * @see io.beethoven.partitur.partitur.PartiturHandler#getEvent()
   * @see #getPartiturHandler()
   * @generated
   */
  EAttribute getPartiturHandler_Event();

  /**
   * Returns the meta object for the containment reference list '{@link io.beethoven.partitur.partitur.PartiturHandler#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see io.beethoven.partitur.partitur.PartiturHandler#getConditions()
   * @see #getPartiturHandler()
   * @generated
   */
  EReference getPartiturHandler_Conditions();

  /**
   * Returns the meta object for the containment reference list '{@link io.beethoven.partitur.partitur.PartiturHandler#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see io.beethoven.partitur.partitur.PartiturHandler#getCommands()
   * @see #getPartiturHandler()
   * @generated
   */
  EReference getPartiturHandler_Commands();

  /**
   * Returns the meta object for class '{@link io.beethoven.partitur.partitur.PartiturCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see io.beethoven.partitur.partitur.PartiturCondition
   * @generated
   */
  EClass getPartiturCondition();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.PartiturCondition#getConditionFunction <em>Condition Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition Function</em>'.
   * @see io.beethoven.partitur.partitur.PartiturCondition#getConditionFunction()
   * @see #getPartiturCondition()
   * @generated
   */
  EAttribute getPartiturCondition_ConditionFunction();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.PartiturCondition#getArg <em>Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Arg</em>'.
   * @see io.beethoven.partitur.partitur.PartiturCondition#getArg()
   * @see #getPartiturCondition()
   * @generated
   */
  EAttribute getPartiturCondition_Arg();

  /**
   * Returns the meta object for class '{@link io.beethoven.partitur.partitur.PartiturCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see io.beethoven.partitur.partitur.PartiturCommand
   * @generated
   */
  EClass getPartiturCommand();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.PartiturCommand#getCommandFunction <em>Command Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Command Function</em>'.
   * @see io.beethoven.partitur.partitur.PartiturCommand#getCommandFunction()
   * @see #getPartiturCommand()
   * @generated
   */
  EAttribute getPartiturCommand_CommandFunction();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.PartiturCommand#getArg <em>Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Arg</em>'.
   * @see io.beethoven.partitur.partitur.PartiturCommand#getArg()
   * @see #getPartiturCommand()
   * @generated
   */
  EAttribute getPartiturCommand_Arg();

  /**
   * Returns the meta object for class '{@link io.beethoven.partitur.partitur.HttpGet <em>Http Get</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Http Get</em>'.
   * @see io.beethoven.partitur.partitur.HttpGet
   * @generated
   */
  EClass getHttpGet();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.HttpGet#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see io.beethoven.partitur.partitur.HttpGet#getUrl()
   * @see #getHttpGet()
   * @generated
   */
  EAttribute getHttpGet_Url();

  /**
   * Returns the meta object for the containment reference '{@link io.beethoven.partitur.partitur.HttpGet#getUriVariables <em>Uri Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Uri Variables</em>'.
   * @see io.beethoven.partitur.partitur.HttpGet#getUriVariables()
   * @see #getHttpGet()
   * @generated
   */
  EReference getHttpGet_UriVariables();

  /**
   * Returns the meta object for the containment reference list '{@link io.beethoven.partitur.partitur.HttpGet#getHeaders <em>Headers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Headers</em>'.
   * @see io.beethoven.partitur.partitur.HttpGet#getHeaders()
   * @see #getHttpGet()
   * @generated
   */
  EReference getHttpGet_Headers();

  /**
   * Returns the meta object for the containment reference list '{@link io.beethoven.partitur.partitur.HttpGet#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see io.beethoven.partitur.partitur.HttpGet#getParams()
   * @see #getHttpGet()
   * @generated
   */
  EReference getHttpGet_Params();

  /**
   * Returns the meta object for class '{@link io.beethoven.partitur.partitur.HttpPost <em>Http Post</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Http Post</em>'.
   * @see io.beethoven.partitur.partitur.HttpPost
   * @generated
   */
  EClass getHttpPost();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.HttpPost#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see io.beethoven.partitur.partitur.HttpPost#getUrl()
   * @see #getHttpPost()
   * @generated
   */
  EAttribute getHttpPost_Url();

  /**
   * Returns the meta object for the containment reference '{@link io.beethoven.partitur.partitur.HttpPost#getUriVariables <em>Uri Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Uri Variables</em>'.
   * @see io.beethoven.partitur.partitur.HttpPost#getUriVariables()
   * @see #getHttpPost()
   * @generated
   */
  EReference getHttpPost_UriVariables();

  /**
   * Returns the meta object for the containment reference list '{@link io.beethoven.partitur.partitur.HttpPost#getHeaders <em>Headers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Headers</em>'.
   * @see io.beethoven.partitur.partitur.HttpPost#getHeaders()
   * @see #getHttpPost()
   * @generated
   */
  EReference getHttpPost_Headers();

  /**
   * Returns the meta object for the containment reference '{@link io.beethoven.partitur.partitur.HttpPost#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see io.beethoven.partitur.partitur.HttpPost#getBody()
   * @see #getHttpPost()
   * @generated
   */
  EReference getHttpPost_Body();

  /**
   * Returns the meta object for class '{@link io.beethoven.partitur.partitur.HttpPut <em>Http Put</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Http Put</em>'.
   * @see io.beethoven.partitur.partitur.HttpPut
   * @generated
   */
  EClass getHttpPut();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.HttpPut#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see io.beethoven.partitur.partitur.HttpPut#getUrl()
   * @see #getHttpPut()
   * @generated
   */
  EAttribute getHttpPut_Url();

  /**
   * Returns the meta object for the containment reference '{@link io.beethoven.partitur.partitur.HttpPut#getUriVariables <em>Uri Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Uri Variables</em>'.
   * @see io.beethoven.partitur.partitur.HttpPut#getUriVariables()
   * @see #getHttpPut()
   * @generated
   */
  EReference getHttpPut_UriVariables();

  /**
   * Returns the meta object for the containment reference list '{@link io.beethoven.partitur.partitur.HttpPut#getHeaders <em>Headers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Headers</em>'.
   * @see io.beethoven.partitur.partitur.HttpPut#getHeaders()
   * @see #getHttpPut()
   * @generated
   */
  EReference getHttpPut_Headers();

  /**
   * Returns the meta object for the containment reference '{@link io.beethoven.partitur.partitur.HttpPut#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see io.beethoven.partitur.partitur.HttpPut#getBody()
   * @see #getHttpPut()
   * @generated
   */
  EReference getHttpPut_Body();

  /**
   * Returns the meta object for class '{@link io.beethoven.partitur.partitur.HttpDelete <em>Http Delete</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Http Delete</em>'.
   * @see io.beethoven.partitur.partitur.HttpDelete
   * @generated
   */
  EClass getHttpDelete();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.HttpDelete#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see io.beethoven.partitur.partitur.HttpDelete#getUrl()
   * @see #getHttpDelete()
   * @generated
   */
  EAttribute getHttpDelete_Url();

  /**
   * Returns the meta object for the containment reference '{@link io.beethoven.partitur.partitur.HttpDelete#getUriVariables <em>Uri Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Uri Variables</em>'.
   * @see io.beethoven.partitur.partitur.HttpDelete#getUriVariables()
   * @see #getHttpDelete()
   * @generated
   */
  EReference getHttpDelete_UriVariables();

  /**
   * Returns the meta object for the containment reference list '{@link io.beethoven.partitur.partitur.HttpDelete#getHeaders <em>Headers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Headers</em>'.
   * @see io.beethoven.partitur.partitur.HttpDelete#getHeaders()
   * @see #getHttpDelete()
   * @generated
   */
  EReference getHttpDelete_Headers();

  /**
   * Returns the meta object for class '{@link io.beethoven.partitur.partitur.HttpHeader <em>Http Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Http Header</em>'.
   * @see io.beethoven.partitur.partitur.HttpHeader
   * @generated
   */
  EClass getHttpHeader();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.HttpHeader#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.beethoven.partitur.partitur.HttpHeader#getName()
   * @see #getHttpHeader()
   * @generated
   */
  EAttribute getHttpHeader_Name();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.HttpHeader#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see io.beethoven.partitur.partitur.HttpHeader#getValue()
   * @see #getHttpHeader()
   * @generated
   */
  EAttribute getHttpHeader_Value();

  /**
   * Returns the meta object for class '{@link io.beethoven.partitur.partitur.UriVariables <em>Uri Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Uri Variables</em>'.
   * @see io.beethoven.partitur.partitur.UriVariables
   * @generated
   */
  EClass getUriVariables();

  /**
   * Returns the meta object for the attribute list '{@link io.beethoven.partitur.partitur.UriVariables#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see io.beethoven.partitur.partitur.UriVariables#getValues()
   * @see #getUriVariables()
   * @generated
   */
  EAttribute getUriVariables_Values();

  /**
   * Returns the meta object for class '{@link io.beethoven.partitur.partitur.QueryParam <em>Query Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query Param</em>'.
   * @see io.beethoven.partitur.partitur.QueryParam
   * @generated
   */
  EClass getQueryParam();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.QueryParam#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.beethoven.partitur.partitur.QueryParam#getName()
   * @see #getQueryParam()
   * @generated
   */
  EAttribute getQueryParam_Name();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.QueryParam#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see io.beethoven.partitur.partitur.QueryParam#getValue()
   * @see #getQueryParam()
   * @generated
   */
  EAttribute getQueryParam_Value();

  /**
   * Returns the meta object for class '{@link io.beethoven.partitur.partitur.HttpBody <em>Http Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Http Body</em>'.
   * @see io.beethoven.partitur.partitur.HttpBody
   * @generated
   */
  EClass getHttpBody();

  /**
   * Returns the meta object for the attribute '{@link io.beethoven.partitur.partitur.HttpBody#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see io.beethoven.partitur.partitur.HttpBody#getValue()
   * @see #getHttpBody()
   * @generated
   */
  EAttribute getHttpBody_Value();

  /**
   * Returns the meta object for enum '{@link io.beethoven.partitur.partitur.PartiturConditionFunction <em>Condition Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Condition Function</em>'.
   * @see io.beethoven.partitur.partitur.PartiturConditionFunction
   * @generated
   */
  EEnum getPartiturConditionFunction();

  /**
   * Returns the meta object for enum '{@link io.beethoven.partitur.partitur.PartiturCommandFunction <em>Command Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Command Function</em>'.
   * @see io.beethoven.partitur.partitur.PartiturCommandFunction
   * @generated
   */
  EEnum getPartiturCommandFunction();

  /**
   * Returns the meta object for enum '{@link io.beethoven.partitur.partitur.EventType <em>Event Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Event Type</em>'.
   * @see io.beethoven.partitur.partitur.EventType
   * @generated
   */
  EEnum getEventType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PartiturFactory getPartiturFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.impl.PartiturWorkflowImpl <em>Workflow</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.impl.PartiturWorkflowImpl
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturWorkflow()
     * @generated
     */
    EClass PARTITUR_WORKFLOW = eINSTANCE.getPartiturWorkflow();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTITUR_WORKFLOW__NAME = eINSTANCE.getPartiturWorkflow_Name();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARTITUR_WORKFLOW__TASKS = eINSTANCE.getPartiturWorkflow_Tasks();

    /**
     * The meta object literal for the '<em><b>Handlers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARTITUR_WORKFLOW__HANDLERS = eINSTANCE.getPartiturWorkflow_Handlers();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.impl.PartiturTaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.impl.PartiturTaskImpl
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturTask()
     * @generated
     */
    EClass PARTITUR_TASK = eINSTANCE.getPartiturTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTITUR_TASK__NAME = eINSTANCE.getPartiturTask_Name();

    /**
     * The meta object literal for the '<em><b>Partitur Http Request</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARTITUR_TASK__PARTITUR_HTTP_REQUEST = eINSTANCE.getPartiturTask_PartiturHttpRequest();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.impl.PartiturHandlerImpl <em>Handler</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.impl.PartiturHandlerImpl
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturHandler()
     * @generated
     */
    EClass PARTITUR_HANDLER = eINSTANCE.getPartiturHandler();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTITUR_HANDLER__NAME = eINSTANCE.getPartiturHandler_Name();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTITUR_HANDLER__EVENT = eINSTANCE.getPartiturHandler_Event();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARTITUR_HANDLER__CONDITIONS = eINSTANCE.getPartiturHandler_Conditions();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARTITUR_HANDLER__COMMANDS = eINSTANCE.getPartiturHandler_Commands();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.impl.PartiturConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.impl.PartiturConditionImpl
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturCondition()
     * @generated
     */
    EClass PARTITUR_CONDITION = eINSTANCE.getPartiturCondition();

    /**
     * The meta object literal for the '<em><b>Condition Function</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTITUR_CONDITION__CONDITION_FUNCTION = eINSTANCE.getPartiturCondition_ConditionFunction();

    /**
     * The meta object literal for the '<em><b>Arg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTITUR_CONDITION__ARG = eINSTANCE.getPartiturCondition_Arg();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.impl.PartiturCommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.impl.PartiturCommandImpl
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturCommand()
     * @generated
     */
    EClass PARTITUR_COMMAND = eINSTANCE.getPartiturCommand();

    /**
     * The meta object literal for the '<em><b>Command Function</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTITUR_COMMAND__COMMAND_FUNCTION = eINSTANCE.getPartiturCommand_CommandFunction();

    /**
     * The meta object literal for the '<em><b>Arg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTITUR_COMMAND__ARG = eINSTANCE.getPartiturCommand_Arg();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.impl.HttpGetImpl <em>Http Get</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.impl.HttpGetImpl
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getHttpGet()
     * @generated
     */
    EClass HTTP_GET = eINSTANCE.getHttpGet();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HTTP_GET__URL = eINSTANCE.getHttpGet_Url();

    /**
     * The meta object literal for the '<em><b>Uri Variables</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HTTP_GET__URI_VARIABLES = eINSTANCE.getHttpGet_UriVariables();

    /**
     * The meta object literal for the '<em><b>Headers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HTTP_GET__HEADERS = eINSTANCE.getHttpGet_Headers();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HTTP_GET__PARAMS = eINSTANCE.getHttpGet_Params();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.impl.HttpPostImpl <em>Http Post</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.impl.HttpPostImpl
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getHttpPost()
     * @generated
     */
    EClass HTTP_POST = eINSTANCE.getHttpPost();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HTTP_POST__URL = eINSTANCE.getHttpPost_Url();

    /**
     * The meta object literal for the '<em><b>Uri Variables</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HTTP_POST__URI_VARIABLES = eINSTANCE.getHttpPost_UriVariables();

    /**
     * The meta object literal for the '<em><b>Headers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HTTP_POST__HEADERS = eINSTANCE.getHttpPost_Headers();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HTTP_POST__BODY = eINSTANCE.getHttpPost_Body();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.impl.HttpPutImpl <em>Http Put</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.impl.HttpPutImpl
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getHttpPut()
     * @generated
     */
    EClass HTTP_PUT = eINSTANCE.getHttpPut();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HTTP_PUT__URL = eINSTANCE.getHttpPut_Url();

    /**
     * The meta object literal for the '<em><b>Uri Variables</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HTTP_PUT__URI_VARIABLES = eINSTANCE.getHttpPut_UriVariables();

    /**
     * The meta object literal for the '<em><b>Headers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HTTP_PUT__HEADERS = eINSTANCE.getHttpPut_Headers();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HTTP_PUT__BODY = eINSTANCE.getHttpPut_Body();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.impl.HttpDeleteImpl <em>Http Delete</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.impl.HttpDeleteImpl
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getHttpDelete()
     * @generated
     */
    EClass HTTP_DELETE = eINSTANCE.getHttpDelete();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HTTP_DELETE__URL = eINSTANCE.getHttpDelete_Url();

    /**
     * The meta object literal for the '<em><b>Uri Variables</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HTTP_DELETE__URI_VARIABLES = eINSTANCE.getHttpDelete_UriVariables();

    /**
     * The meta object literal for the '<em><b>Headers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HTTP_DELETE__HEADERS = eINSTANCE.getHttpDelete_Headers();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.impl.HttpHeaderImpl <em>Http Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.impl.HttpHeaderImpl
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getHttpHeader()
     * @generated
     */
    EClass HTTP_HEADER = eINSTANCE.getHttpHeader();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HTTP_HEADER__NAME = eINSTANCE.getHttpHeader_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HTTP_HEADER__VALUE = eINSTANCE.getHttpHeader_Value();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.impl.UriVariablesImpl <em>Uri Variables</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.impl.UriVariablesImpl
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getUriVariables()
     * @generated
     */
    EClass URI_VARIABLES = eINSTANCE.getUriVariables();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute URI_VARIABLES__VALUES = eINSTANCE.getUriVariables_Values();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.impl.QueryParamImpl <em>Query Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.impl.QueryParamImpl
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getQueryParam()
     * @generated
     */
    EClass QUERY_PARAM = eINSTANCE.getQueryParam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUERY_PARAM__NAME = eINSTANCE.getQueryParam_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUERY_PARAM__VALUE = eINSTANCE.getQueryParam_Value();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.impl.HttpBodyImpl <em>Http Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.impl.HttpBodyImpl
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getHttpBody()
     * @generated
     */
    EClass HTTP_BODY = eINSTANCE.getHttpBody();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HTTP_BODY__VALUE = eINSTANCE.getHttpBody_Value();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.PartiturConditionFunction <em>Condition Function</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.PartiturConditionFunction
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturConditionFunction()
     * @generated
     */
    EEnum PARTITUR_CONDITION_FUNCTION = eINSTANCE.getPartiturConditionFunction();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.PartiturCommandFunction <em>Command Function</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.PartiturCommandFunction
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getPartiturCommandFunction()
     * @generated
     */
    EEnum PARTITUR_COMMAND_FUNCTION = eINSTANCE.getPartiturCommandFunction();

    /**
     * The meta object literal for the '{@link io.beethoven.partitur.partitur.EventType <em>Event Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.beethoven.partitur.partitur.EventType
     * @see io.beethoven.partitur.partitur.impl.PartiturPackageImpl#getEventType()
     * @generated
     */
    EEnum EVENT_TYPE = eINSTANCE.getEventType();

  }

} //PartiturPackage
