/**
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.partitur;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.beethoven.partitur.partitur.PartiturCondition#getConditionFunction <em>Condition Function</em>}</li>
 *   <li>{@link io.beethoven.partitur.partitur.PartiturCondition#getArg <em>Arg</em>}</li>
 * </ul>
 *
 * @see io.beethoven.partitur.partitur.PartiturPackage#getPartiturCondition()
 * @model
 * @generated
 */
public interface PartiturCondition extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition Function</b></em>' attribute.
   * The literals are from the enumeration {@link io.beethoven.partitur.partitur.PartiturConditionFunction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition Function</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition Function</em>' attribute.
   * @see io.beethoven.partitur.partitur.PartiturConditionFunction
   * @see #setConditionFunction(PartiturConditionFunction)
   * @see io.beethoven.partitur.partitur.PartiturPackage#getPartiturCondition_ConditionFunction()
   * @model
   * @generated
   */
  PartiturConditionFunction getConditionFunction();

  /**
   * Sets the value of the '{@link io.beethoven.partitur.partitur.PartiturCondition#getConditionFunction <em>Condition Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition Function</em>' attribute.
   * @see io.beethoven.partitur.partitur.PartiturConditionFunction
   * @see #getConditionFunction()
   * @generated
   */
  void setConditionFunction(PartiturConditionFunction value);

  /**
   * Returns the value of the '<em><b>Arg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arg</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg</em>' attribute.
   * @see #setArg(String)
   * @see io.beethoven.partitur.partitur.PartiturPackage#getPartiturCondition_Arg()
   * @model
   * @generated
   */
  String getArg();

  /**
   * Sets the value of the '{@link io.beethoven.partitur.partitur.PartiturCondition#getArg <em>Arg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg</em>' attribute.
   * @see #getArg()
   * @generated
   */
  void setArg(String value);

} // PartiturCondition
