/**
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.partitur;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uri Variables</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.beethoven.partitur.partitur.UriVariables#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see io.beethoven.partitur.partitur.PartiturPackage#getUriVariables()
 * @model
 * @generated
 */
public interface UriVariables extends EObject
{
  /**
   * Returns the value of the '<em><b>Values</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Values</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' attribute list.
   * @see io.beethoven.partitur.partitur.PartiturPackage#getUriVariables_Values()
   * @model unique="false"
   * @generated
   */
  EList<String> getValues();

} // UriVariables
