/**
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.partitur.impl;

import io.beethoven.partitur.partitur.PartiturPackage;
import io.beethoven.partitur.partitur.PartiturTask;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Task</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.beethoven.partitur.partitur.impl.PartiturTaskImpl#getName <em>Name</em>}</li>
 *   <li>{@link io.beethoven.partitur.partitur.impl.PartiturTaskImpl#getPartiturHttpRequest <em>Partitur Http Request</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PartiturTaskImpl extends MinimalEObjectImpl.Container implements PartiturTask
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getPartiturHttpRequest() <em>Partitur Http Request</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPartiturHttpRequest()
   * @generated
   * @ordered
   */
  protected EObject partiturHttpRequest;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PartiturTaskImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PartiturPackage.Literals.PARTITUR_TASK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PartiturPackage.PARTITUR_TASK__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EObject getPartiturHttpRequest()
  {
    return partiturHttpRequest;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPartiturHttpRequest(EObject newPartiturHttpRequest, NotificationChain msgs)
  {
    EObject oldPartiturHttpRequest = partiturHttpRequest;
    partiturHttpRequest = newPartiturHttpRequest;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PartiturPackage.PARTITUR_TASK__PARTITUR_HTTP_REQUEST, oldPartiturHttpRequest, newPartiturHttpRequest);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPartiturHttpRequest(EObject newPartiturHttpRequest)
  {
    if (newPartiturHttpRequest != partiturHttpRequest)
    {
      NotificationChain msgs = null;
      if (partiturHttpRequest != null)
        msgs = ((InternalEObject)partiturHttpRequest).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PartiturPackage.PARTITUR_TASK__PARTITUR_HTTP_REQUEST, null, msgs);
      if (newPartiturHttpRequest != null)
        msgs = ((InternalEObject)newPartiturHttpRequest).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PartiturPackage.PARTITUR_TASK__PARTITUR_HTTP_REQUEST, null, msgs);
      msgs = basicSetPartiturHttpRequest(newPartiturHttpRequest, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PartiturPackage.PARTITUR_TASK__PARTITUR_HTTP_REQUEST, newPartiturHttpRequest, newPartiturHttpRequest));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PartiturPackage.PARTITUR_TASK__PARTITUR_HTTP_REQUEST:
        return basicSetPartiturHttpRequest(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PartiturPackage.PARTITUR_TASK__NAME:
        return getName();
      case PartiturPackage.PARTITUR_TASK__PARTITUR_HTTP_REQUEST:
        return getPartiturHttpRequest();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PartiturPackage.PARTITUR_TASK__NAME:
        setName((String)newValue);
        return;
      case PartiturPackage.PARTITUR_TASK__PARTITUR_HTTP_REQUEST:
        setPartiturHttpRequest((EObject)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PartiturPackage.PARTITUR_TASK__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PartiturPackage.PARTITUR_TASK__PARTITUR_HTTP_REQUEST:
        setPartiturHttpRequest((EObject)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PartiturPackage.PARTITUR_TASK__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PartiturPackage.PARTITUR_TASK__PARTITUR_HTTP_REQUEST:
        return partiturHttpRequest != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //PartiturTaskImpl
