/**
 * generated by Xtext 2.12.0
 */
package io.beethoven.partitur.partitur.impl;

import io.beethoven.partitur.partitur.PartiturCommand;
import io.beethoven.partitur.partitur.PartiturCommandFunction;
import io.beethoven.partitur.partitur.PartiturPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.beethoven.partitur.partitur.impl.PartiturCommandImpl#getCommandFunction <em>Command Function</em>}</li>
 *   <li>{@link io.beethoven.partitur.partitur.impl.PartiturCommandImpl#getArg <em>Arg</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PartiturCommandImpl extends MinimalEObjectImpl.Container implements PartiturCommand
{
  /**
   * The default value of the '{@link #getCommandFunction() <em>Command Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCommandFunction()
   * @generated
   * @ordered
   */
  protected static final PartiturCommandFunction COMMAND_FUNCTION_EDEFAULT = PartiturCommandFunction.START_TASK;

  /**
   * The cached value of the '{@link #getCommandFunction() <em>Command Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCommandFunction()
   * @generated
   * @ordered
   */
  protected PartiturCommandFunction commandFunction = COMMAND_FUNCTION_EDEFAULT;

  /**
   * The default value of the '{@link #getArg() <em>Arg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArg()
   * @generated
   * @ordered
   */
  protected static final String ARG_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getArg() <em>Arg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArg()
   * @generated
   * @ordered
   */
  protected String arg = ARG_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PartiturCommandImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PartiturPackage.Literals.PARTITUR_COMMAND;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PartiturCommandFunction getCommandFunction()
  {
    return commandFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCommandFunction(PartiturCommandFunction newCommandFunction)
  {
    PartiturCommandFunction oldCommandFunction = commandFunction;
    commandFunction = newCommandFunction == null ? COMMAND_FUNCTION_EDEFAULT : newCommandFunction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PartiturPackage.PARTITUR_COMMAND__COMMAND_FUNCTION, oldCommandFunction, commandFunction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getArg()
  {
    return arg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setArg(String newArg)
  {
    String oldArg = arg;
    arg = newArg;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PartiturPackage.PARTITUR_COMMAND__ARG, oldArg, arg));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PartiturPackage.PARTITUR_COMMAND__COMMAND_FUNCTION:
        return getCommandFunction();
      case PartiturPackage.PARTITUR_COMMAND__ARG:
        return getArg();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PartiturPackage.PARTITUR_COMMAND__COMMAND_FUNCTION:
        setCommandFunction((PartiturCommandFunction)newValue);
        return;
      case PartiturPackage.PARTITUR_COMMAND__ARG:
        setArg((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PartiturPackage.PARTITUR_COMMAND__COMMAND_FUNCTION:
        setCommandFunction(COMMAND_FUNCTION_EDEFAULT);
        return;
      case PartiturPackage.PARTITUR_COMMAND__ARG:
        setArg(ARG_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PartiturPackage.PARTITUR_COMMAND__COMMAND_FUNCTION:
        return commandFunction != COMMAND_FUNCTION_EDEFAULT;
      case PartiturPackage.PARTITUR_COMMAND__ARG:
        return ARG_EDEFAULT == null ? arg != null : !ARG_EDEFAULT.equals(arg);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (commandFunction: ");
    result.append(commandFunction);
    result.append(", arg: ");
    result.append(arg);
    result.append(')');
    return result.toString();
  }

} //PartiturCommandImpl
